app/__init__.py
import os

from celery import Celery
from flask import Flask


def make_celery(app):
    celery = Celery(
        app.import_name,
        backend=app.config['CELERY_RESULT_BACKEND'],
        broker=app.config['CELERY_BROKER_URL'],
    )
    celery.conf.update(app.config)
    TaskBase = celery.Task

    class ContextTask(TaskBase):
        abstract = True

        def __call__(self, *args, **kwargs):
            with app.app_context():
                return TaskBase.__call__(self, *args, **kwargs)
    celery.Task = ContextTask
    return celery


def make_app():
    app = Flask(__name__)
    app.secret_key = 'secret'
    app.session_cookie_name = 'flask_session'

    app.config.update(
        CELERY_BROKER_URL=os.environ['REDIS_URL'],
        CELERY_RESULT_BACKEND=os.environ['REDIS_URL'],
    )
    return app

app = make_app()
celery = make_celery(app)

from app.controllers import followers_app
app.register_blueprint(followers_app)

app/controllers.py
from flask import (
    Blueprint,
    jsonify,
    redirect,
    render_template,
    request,
    session,
)

from app.workers import (
    get_async_result,
    get_followers_ids,
)
from app.twitter_client import twitter_oauth_client


followers_app = Blueprint(
    'followers_app',
    __name__,
    template_folder='templates',
)


@followers_app.route('/')
def index():
    return render_template('index.html')


@followers_app.route('/auth')
def auth():
    url, request_token = twitter_oauth_client.get_authorization_url()
    session['request_token'] = request_token
    return redirect(url)


@followers_app.route('/callback')
def twitter_callback():
    session['oauth_token'] = request.args.get('oauth_token')
    session['oauth_verifier'] = request.args.get('oauth_verifier')
    return redirect('/followers/followers')


@followers_app.route('/followers/followers')
def followers():
    request_token = session['oauth_token']
    oauth_verifier = session['oauth_verifier']
    async_res = get_followers_ids.apply_async(
        (request_token, oauth_verifier),
        serializer='json',
    )
    session['TASK_ID'] = async_res.id
    return render_template('loading.html')


@followers_app.route('/loading')
def check_if_complete():
    async_res_id = session.get('TASK_ID')
    if async_res_id is None:
        jsonify({'status': 'RUNNING', 'result': 'Loading ...'})
    async_res = get_async_result(async_res_id)

    if async_res.failed():
        return jsonify({'status': 'ERROR', 'result': 'Try again'})
    elif async_res.successful():
        result = async_res.get()
        session['followers'] = result
        return jsonify({
            'status': 'OK',
            'result': render_template(
                'template.html',
                data=result
            )
        })
    else:
        return jsonify({'status': 'RUNNING', 'result': 'Loading ...'})


@followers_app.route('/followers_json')
def followers_json():
    data = session['followers']
    return jsonify(data)

app/twitter_client/__init__.py
from .oauth import TwitterOAuthClient


twitter_oauth_client = TwitterOAuthClient(
    consumer_key='gb3iFvqTHwR99wBcvsx0TiOTm',
    consumer_secret='IP5rNdZ9YX4SMGgc6cgNG4g9AcgiD00ET6S7DZlb6Ee95CUgTC',
    callback_url='https://my2ndlinefollowers.herokuapp.com/callback',
)

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>
    <p>
        <a href="{{ url_for('followers_app.auth') }}">Connect Your Twitter Account and see Your followers.</a>
    </p>
</body>
</html>

app/templates/loading.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Result</title>
</head>
<body>
<p>What's up:</p>
<span class="result"></span>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
  <script>
    (function() {
      var status = $('.result'),
        poll = function() {
          $.ajax({
            url: '/loading',
            dataType: 'json',
            type: 'get',
            success: function(data) {
              console.log(data);
              status.text('Initialize');
              if ( data.status == 'OK' ) {
                status.html(data.result);
                clearInterval(pollInterval);
              }
              else if ( data.status == 'ERROR' ) {
                status.text(data.result);
                clearInterval(pollInterval);
              }
              else {
                status.text(data.result);
              }
            },
            error: function() { // error logging
              console.log('Error!');
            }
          });
        },
        pollInterval = setInterval(function() {
          poll();
          }, 10000);
        poll();
    })();
  </script>
</body>
</html>

app/templates/template.html
<table border="1">
    <tr>
        <th>Name</th>
        <th>No.</th>
    </tr>
    {% for key, value in data.items() %}
    <tr>
        <th align="left">{{key}}</th>
        <th>{{value}}</th>
    </tr>
    {% endfor %}
</table>

<p></p><a href="{{ url_for('followers_app.followers_json') }}">See as JSON</a></p>